### ISSUE TITLE
Meta support

### ISSUE THREAD

**Issue by VincentGijsen** [tomaskovacik/IS2020#2]
Hi Tomas,

Just wanted to let you know I got the meta-info working on my project, which originated quite strongly from your library, so only fair to let you know i guess. Should you like to backport some of my stuff in your library, regarding meta-data, feel free.

side note: 

- I had issues with android (9, stock rom sony), so left that, and used my iPhone (which has much better BT stack as I've noticed in a other project). It still pretty rough, but works at least with the ipone.
- inital version gets all meta-data in single event, and as MTU size is pretty big, my buffers are so aswell (2x250 uint8_t), not sure how an basic ArduinoUno is occupied RAM-wise, but could require some more optimizing. This add up quite fast, especilaly with classical syphonies and extensive artists, ...

invoking command:
https://github.com/VincentGijsen/MelbusRtos/blob/3d812d4549950435f2c2a302021bebe854f464c5/src/IS2020/AVRCP.c#L37

handler sections:
https://github.com/VincentGijsen/MelbusRtos/blob/3d812d4549950435f2c2a302021bebe854f464c5/src/IS2020/IS2020.c#L294

https://github.com/VincentGijsen/MelbusRtos/blob/3d812d4549950435f2c2a302021bebe854f464c5/src/IS2020/IS2020.c#L360

**Comment by tomaskovacik** [comment]
hello, hello, oh that's amazing! thx for the info! just a few days back I fired my protoboard (actually also stm32f..... (the one from blue-pill) with bm20 bt module ) to work on this but I did not make any progress (I fall asleep :D ), so I really like this. :)

if you have any working designs I would like to consult HW part, or you just wire it all together? I have a pretty big problem with noise (BT communication?) in the audio part if some sort of preamp is used.

anyway, thx for info again! I will mention you in code and here.

t.

**Comment by VincentGijsen** [comment]
Well,

So far, no real hw schema, just headphones and a breadboard with your
board  from Tindie, a bluepill as well , and some wiring for tx, rx and
gnd. Added two ~ 1? KOhm resistors to limit current between BM20 and
bluepill.

So far ugly power; read  (USB for BM20, USB (vcp +power) for bluepill and
programmer (no vcc) all on my laptop. Yet with my headphones, quite decent
audio. Yes the order of power up does matter sometime... So pretty grap I
guess.

The end-version (for my Volvo car stock radio) will use a groundloop
isolator, perhaps such (bulky) component handles your issues as well?

Unfortunately, a quick test with Android resulted in a avrcp issue
reported. So unfortunately my daily driver phone doesnt do the meta with
this code.

Perhaps I need to better understand the Passthrough stuff in the avrcp-1.3
spec ... Might be related... If only docu was better.

Regarding audio, I use the cappless setting from the IS2020 tools.. at some
point changed this, my audio sounded like if there was a short... took me
while to locate this seemingly vague (for me) setting for the dacs outputs.


Hopefully we can sort out this meta thing for Android too.

Do keep me posted on your progress, if you like, i can do the same .

Cheers!

**Comment by tomaskovacik** [comment]
Did you try this on android?In developer optionsOn 18 Jan 2020 23:18, Vincent Gijsen <notifications@github.com> wrote:Well,



So far, no real hw schema, just headphones and a breadboard with your

board  from Tindie, a bluepill as well , and some wiring for tx, rx and

gnd. Added two ~ 1? KOhm resistors to limit current between BM20 and

bluepill.



So far ugly power; read  (USB for BM20, USB (vcp +power) for bluepill and

programmer (no vcc) all on my laptop. Yet with my headphones, quite decent

audio. Yes the order of power up does matter sometime... So pretty grap I

guess.



The end-version (for my Volvo car stock radio) will use a groundloop

isolator, perhaps such (bulky) component handles your issues as well?



Unfortunately, a quick test with Android resulted in a avrcp issue

reported. So unfortunately my daily driver phone doesnt do the meta with

this code.



Perhaps I need to better understand the Passthrough stuff in the avrcp-1.3

spec ... Might be related... If only docu was better.



Regarding audio, I use the cappless setting from the IS2020 tools.. at some

point changed this, my audio sounded like if there was a short... took me

while to locate this seemingly vague (for me) setting for the dacs outputs.





Hopefully we can sort out this meta thing for Android too.



Do keep me posted on your progress, if you like, i can do the same .



Cheers!

**Comment by VincentGijsen** [comment]
Hi Tomas,

small update, after unlocking my bootloader, and flashing a custom rom (without all the bloatware), of android-PIE my phone now spits-out avrcp-meta info, with the unchanged code in the repo. i set the avrcp setting to 1.5. it was a real hassle to get the paring to going again, probably some reminant in the IS2020 eprom .... but iphone, just flawless paring each time...

my phone experia xz1 compact, tried my wife's phone (xiaomi a2), also troubles with avrcp...

but as said, my experiences with android (9) and its bluetooth stack have been horrible sofar... lasttime it was th WideBand codecs for speech.... I seriously doubt that my next phone will also be an android....

anywas, have fun, hope you have that should you use an android, your ride will be more smooth.

**Comment by tomaskovacik** [comment]
so, many thx! it works!

AVRCP_List_Player_Attributes
 [1a,0,a,48,0,0,19,58,17,0,0,1,0,]
PDU Id: 17 AVRCP_DISPLAYABLE_CHARSET [1a,0,c,48,0,0,19,58,10,0,0,9,3,7,1,2,5,8,9,a,b,]
PDU Id: 10 AVRCP_GET_CAPABILITIESAVRCP_EVENT_STATUS_CHANGEDAVRCP_EVENT_TRACK_CHANGEDAVRCP_EVENT_PLAYBACK_POS_CHANGEDAVRCP_EVENT_PLAYER_APPLICATION_SETTING_CHANGEDAVRCP_EVENT_NOW_PLAYING_CONTENT_CHANGEDAVRCP_EVENT_AVAILABLE_PLAYERS_CHANGEDAVRCP_EVENT_ADDRESSED_PLAYER_CHANGED [1a,0,c,48,0,0,19,58,11,0,0,3,2,2,3,]
PDU Id: 11 AVRCP_LIST_PLAYER_ATTRIBUTESAVRCP_Get_Player_Attribute_Text
AVRCP_Get_Player_Attribute_Text
 [1a,0,f,48,0,0,19,58,31,0,0,2,1,1,]
PDU Id: 31 AVRCP_REGISTER_NOTIFICATIONAVRCP_EVENT_STATUS_CHANGED [1a,0,f,48,0,0,19,58,31,0,0,9,2,0,0,0,0,0,0,0,0,]
PDU Id: 31 AVRCP_REGISTER_NOTIFICATIONAVRCP_EVENT_TRACK_CHANGEDAVRCP Get element attributes command
 [1a,0,f,48,0,0,19,58,31,0,0,5,5,0,0,8b,8c,]
PDU Id: 31 AVRCP_REGISTER_NOTIFICATIONAVRCP_EVENT_PLAYBACK_POS_CHANGED [1a,0,f,48,0,0,19,58,31,0,0,6,8,2,2,1,3,1,]
PDU Id: 31 AVRCP_REGISTER_NOTIFICATIONAVRCP_EVENT_PLAYER_APPLICATION_SETTING_CHANGED [1a,0,f,48,0,0,19,58,31,0,0,1,9,]
PDU Id: 31 AVRCP_REGISTER_NOTIFICATION [1a,0,f,48,0,0,19,58,31,0,0,1,a,]
PDU Id: 31 AVRCP_REGISTER_NOTIFICATION [1a,0,f,48,0,0,19,58,31,0,0,5,b,0,2,0,0,]
PDU Id: 31 AVRCP_REGISTER_NOTIFICATIONAVRCP_EVENT_ADDRESSED_PLAYER_CHANGED [1a,0,c,48,0,0,19,58,15,0,0,5,2,]
PDU Id: 15 AVRCP_GET_PLAYER_ATTRIBUTE_TEXT [1a,0,c,48,0,0,19,58,15,0,0,5,3,]
PDU Id: 15 AVRCP_GET_PLAYER_ATTRIBUTE_TEXT [1a,0,c,48,0,0,19,58,20,0,0,8c,7,0,0,0,1,0,6a,0,b,44,61,6e,67,65,72,20,5a,6f,6e,65,0,0,0,2,0,6a,0,9,41,6d,61,72,61,6e,74,68,65,0,0,0,3,0,6a,0,11,4d,61,73,73,69,76,65,20,41,64,64,69,63,74,69,76,65,0,0,0,4,0,6a,0,1,31,0,0,0,5,0,6a,0,1,31,0,0,0,6,0,6a,0,26,50,6f,77,65,72,2f,20,4d,65,6c,6f,64,69,63,20,44,65,61,74,68,20,4d,65,74,61,6c,20,2f,20,4d,65,74,61,6c,63,6f,72,65,0,0,0,7,0,6a,0,6,31,38,31,38,31,31,]
PDU Id: 20 AVRCP_GET_ELEMENT_ATTRIBUTES

which straslate to:

HX«HXÊ«í¬íºíÊíí«í­ííHXHX11ÊíHX11Ê¬íHX11ÊºíHX11ÊÊíHX11ÊHX11ÊHX11Ê­ííHXHXHX jDanger ZonejAmaranthejMassive Addictivej1j1j&Power/ Melodic Death Metal / Metalcorej181811 

I use bm20 with samsung s9, also android 9

t.

**Comment by tomaskovacik** [comment]
hello again, 



and surprise it even get metadata from youtube app also (last player usd was youtube app)

Event from module:  [1a,0,c,48,0,0,19,58,20,0,0,8b,7,0,0,0,1,0,6a,0,2a,4e,69,63,65,20,64,61,79,20,74,6f,20,67,6f,20,74,6f,20,74,68,65,20,70,75,62,20,2d,20,43,4f,53,4d,49,43,20,50,53,59,43,48,4f,53,0,0,0,2,0,6a,0,10,47,69,6c,6c,69,61,6e,20,4d,63,4b,69,6e,6c,65,79,0,0,0,3,0,6a,0,10,47,69,6c,6c,69,61,6e,20,4d,63,4b,69,6e,6c,65,79,0,0,0,4,0,6a,0,1,31,0,0,0,5,0,6a,0,1,31,0,0,0,6,0,6a,0,0,0,0,0,7,0,6a,0,6,32,32,32,30,30,30,]
Decoded PDU event: AVRCP_GET_ELEMENT_ATTRIBUTES
Title: Nice day to go to the pub - COSMIC PSYCHOS
Artist: Gillian McKinley
Albun: Gillian McKinley
Track: 1
Number of tracks: 1
Genre: 
Duration: 222000

**Comment by tomaskovacik** [comment]
hello, vincent

I have time to play with it little, 

regarding pairing, every time I reset module I lose information about paired modules , I cannot use connect last paired device ( profileLinkBack() function ) When I disconnect from device then I can reconnect from module by calling profileLinkback(4,X,7), where X=>device Id in table of paired devices ( readPairedDeviceRecord() ) this sux ... :/ 

next strange issue:
when using samsung music player or google play music, when I change track I got track_changed notification only once after registering of this notification 

did this works for you?

**Comment by VincentGijsen** [comment]
Hi Tomas,

Im also working on the AVRCP event notifications atm, and notice issues
when registering them. When validating acks from BTM. Also seem to get
timeouts sometimes, looks like BTM is busy processing or perhaps waiting
for phone when forwarding or something.

I just checked the ACKing of events produced by the BTM.

Suspecr registering these callbacks doesn't go fast or something. Next step
to implement wait cycle (up to 8sec) as described in PDF.

And checkering avrcp spec1.3 with your initial implementation.

But in general just track change and NMI events (play/pause) work right now.

Regarding setting the module, if you mean 'pressing resetvbutton button' it
reconnects everytime to phone correctly, without specific (or any
commands). I do recall making changes with config tool to make it boot on
'ac' power. I also enabled multiple/parallel connections perhaps it
matters?!

Did you try sending power on NMI cmd ? (Saw it just jet in PDf, just a wild
guess)


I'll give you a ping, should I find a fix.

Cheers,

**Comment by tomaskovacik** [comment]
hi again,


throwing all registerins_nodtification as I did [here](https://github.com/tomaskovacik/IS2020/blob/master/src/AVRCP.cpp#L270) is not good that's right, I have to clean event handling, while I started to write this lib I did not have an idea what I'm doid (not that I have it now :D, I'm electronic not SW eng. :) )


anyway back to the problem.

datasheet to BM20 says it is AVRCP1.5 so I'm using it and in android in developer options, I change my default avrcp to 1.5 ( but I will try 1.3, but again it will be deprecated [next year](https://www.bluetooth.com/specifications/archived-specifications/) )

regarding connecting to the last device:

I did not have the problem when I disconnect module from phone by serial command or phone from module. Then I can simply profile link back or mmi action linkLastDevice, both works. but after total pwoer cycle, all pairing information are lost and I get "command disallow" for porfileLinkBack function (obviously, as readPairedDeviceRecord return nothing profileLinkBack function can not work). Fro MMI action linkLastDevice I got no response from the module, just ack that command was received and is valid (my guess is, that MMI commands are allowed and crc is ok :) )

my module is also in always power-on mode. and also I can connect 2 BT devices to the module. I have to check my settings ... or othe module.

**Comment by VincentGijsen** [comment]
strange,

once my module is paired, it keeps working after powercycles.

regarding notification, perhaps the SPEC is to be read, that each notificaiton (when triggerd, must be re-requested).

it doesn't state this particularly clear but if you look at chapter 5.5 of the(AVRCP_SPEC_V1.5.pdf) mentions amongst others:
```
5. On the occurrence of a registered event, TG device shall send a CHANGED
response to the CT with the current status
6. As per AV/C protocol a NOTIFY command terminates after providing a
corresponding CHANGED. It is recommended that CT devices that need periodic
updates on selected events re-register for those events after the receipt of the
corresponding CHANGED as they will only receive an update when there is an
outstanding NOTIFY to complete.
7. As per AVCTP, there shall be only 16 outstanding transaction labels at any
instant of time on each AVCTP channel. This shall limit the number of events that
can be simultaneously registered or pending response to 15.

```

so you simply have to re-request a notification for a particular event, after it has been 'fired', so the 2nd occurrence, right after the first ACK, the INTERMEDIATE is fired, and than, eg, when track changes or POS_UPDATE.

I guess more housekeeping, but appart from this, doable. You also need to watch that youre not having more than 16 event-type requests at the same time.

**Comment by tomaskovacik** [comment]
and how did you reconect to phone? calling which function?

**Comment by VincentGijsen** [comment]
The reconnecting is never an issue for me, it just works after the powering up. i suspect strange with the EEPROM setttings.

prehaps useing the tools to mange the IS2020 to re-flash it?

regarding the re-subscribing of events, i have fixed it using the following contruct:
```
//avrcp case:
                        uint8_t devId = event[IS2020_EVENT_IDX_DEVID];
			uint8_t avrcpResponse = event[2]; //byte 0 of AVRCP pgk
			uint8_t subUnitId = event[3];
			uint8_t opcode = event[4];
			uint8_t compId[3] = { event[5], event[6], event[7] };
			uint8_t pdu = event[8];
			uint8_t res = event[9];
			uint8_t paramLen = (event[10] << 8) + event[11];
			uint8_t a = 1;
...

if (pdu == AVRCP_REGISTER_NOTIFICATION) {

				switch (event[12]) {
					case AVRCP_EVENT_STATUS_CHANGED: {

						switch (event[13]) {
							case AVRCP_PLAY_STATUS_STOPPED:
								postApplicationEvent(EVT_MUSIC_STOP);
								break;

							case AVRCP_PLAY_STATUS_PLAYING:
								postApplicationEvent(EVT_MUSIC_PLAY);
								break;

							case AVRCP_PLAY_STATUS_PAUSED:
								postApplicationEvent(EVT_MUSIC_PAUSE);
								break;

							case AVRCP_PLAY_STATUS_FWD_SEEK:
								postApplicationEvent(EVT_MUSIC_FF);
								break;

							case AVRCP_PLAY_STATUS_REV_SEEK:
								postApplicationEvent(EVT_MUSIC_FR);

								break;

							case AVRCP_PLAY_STATUS_ERROR:
								break;
						}
					}
						break;

					case AVRCP_EVENT_TRACK_CHANGED:

						for (uint16_t parameter_byte = 14; parameter_byte < length;
								parameter_byte++) {
							//DBG(String(event[parameter_byte], HEX));
						}
						usb_vcp_send_strn("TRKch\r\n", 7);
						//IS2020_AVRCP_REGISTER_NOTIFICATION_TRACKCHANGED(0);
						switch (avrcpResponse) {
							case AVRCP_EVENT_EVENTMSGTYPE_NOTIFY:
								break;
							case AVRCP_EVENT_EVENTMSGTYPE_INTERIM:
								break;
							case AVRCP_EVENT_EVENTMSGTYPE_CHANGED:
								//re-active event
								IS2020_AVRCP_REGISTER_NOTIFICATION_TRACKCHANGED(0);
								postApplicationEvent(EVT_BM_MUSIC_TRACK_CHANGED);
						}

						break;

					case AVRCP_EVENT_PLAYBACK_POS_CHANGED:
						IS2020_playback_position = event[13] << 24 | event[14] << 16
								| event[15] << 8 | event[16];
						usb_vcp_send_strn("POSch\r\n", 7);
						//req-requist next update
						switch (avrcpResponse) {
							case AVRCP_EVENT_EVENTMSGTYPE_NOTIFY:
								break;
							case AVRCP_EVENT_EVENTMSGTYPE_INTERIM:
								break;
							case AVRCP_EVENT_EVENTMSGTYPE_CHANGED:
								//re-active event
								IS2020_AVRCP_REGISTER_NOTIFICATION_POSCHANGED(0);
								postApplicationEvent(EVT_BM_MUSIC_TRACK_POS_CHANGED);
						}

						break;

				}		//switch
...
```
see https://github.com/VincentGijsen/MelbusRtos/blob/5385749d787d6ca79a2cdc93ff4f61466e6d4629/src/IS2020/IS2020.c#L377 for full code

You will see that this particular section (below) will only resubscribe after the event has been reported with the changed type, the other two cases come earlier. You will also have to take care that some events are automatically canceld by others (e.g. player-change, track-change). so i probably re-subscribe periodically all as quick-n-dirty solution:

```
	switch (avrcpResponse) {
							case AVRCP_EVENT_EVENTMSGTYPE_NOTIFY:
								break;
							case AVRCP_EVENT_EVENTMSGTYPE_INTERIM:
								break;
							case AVRCP_EVENT_EVENTMSGTYPE_CHANGED:
								//re-active event
								IS2020_AVRCP_REGISTER_NOTIFICATION_POSCHANGED(0);
								postApplicationEvent(EVT_BM_MUSIC_TRACK_POS_CHANGED);
						}
```

in any case with this in place, it now runs pretty solid, (in my case) re-request meta info upon every track-change

**Comment by tomaskovacik** [comment]
thx! I was trying to see some difference in packets, but it was too late obviously :)

**Comment by tomaskovacik** [comment]
pairing "issue" fixed, changing "Enter pairing mode when Power On" to enable fixed the issue.

FIY:
- I use the simple program to flash BM20 while soldered on board, I connect two unused pins of stm32 to P2_0 on BM20 and to BM20 reset. and in this simple program, I just pull P2_0 high and do hw reset of BM20.  Next goes infinite loop which reads from one serial and writes to serial port connected to BM20 (and vice versa)

- when looking into SW provided for BM20, I realize that tool IS2020_002 have PBAP option, but this is for older firmware and BM20 is rom based, so I take look at flash based modules and BM64 looks promising, also the footprint is similar and should work as a direct swap. 
![image](https://user-images.githubusercontent.com/4346464/73175869-6dc08280-410b-11ea-82f4-11bafacf4e8e.png)

**Comment by tomaskovacik** [comment]
I changed defines for RESPONSEs, there is one more which is important: REJECT = 0x0A. so I change names of these defines and also rewrite part of code which detect reject and the reason of the rejection:

https://github.com/tomaskovacik/IS2020/blob/master/src/events.cpp#L855

**Comment by tomaskovacik** [comment]
Hello Vincent, 


I clean it all up little bit (this function for know requests all elements, but will be probably rewritten with some sort of selection of elements in the future)
https://github.com/tomaskovacik/IS2020/blob/1d7c8a9d66c9a6fe5e2171f061a0d85106fce0c9/src/AVRCP.cpp#L104

and the other version for requesting all meta data:
https://github.com/tomaskovacik/IS2020/blob/1d7c8a9d66c9a6fe5e2171f061a0d85106fce0c9/src/AVRCP.cpp#L142
