### ISSUE TITLE
No communication

### ISSUE THREAD

**Issue by PBurdelak** [tomaskovacik/IS2020#3]
I'm trying to communicate with the Arduino through UART using your library.
I have a problem because I don't have any response from BM20.
Is it enough to connect Arduino's RX/TX to BM20's HCI_RXD/HCI_TXD? Or should I connect something else (eg. turn on command mode)? Can you give me any advice with that?

**Comment by tomaskovacik** [comment]
serial port is disabled by default,

you must uploadt eeprom with enabled serial port, follow this guide: http://ww1.microchip.com/downloads/en/DeviceDoc/BM20_EVB_V4_USER_GUIDE.pdf

or you can use this sketch
https://github.com/tomaskovacik/kicad-library/tree/master/library/datasheet/BM20/programing_BM20_sketch

 and upload my configuration (not firmware stated here previously)  

https://github.com/tomaskovacik/kicad-library/blob/master/library/datasheet/BM20/BM20.ipf

using EEPROM_Tool.exe from
https://www.microchip.com/wwwproducts/en/BM20 -> Documentation  -> BM20_203 Tools Set -> EEPROM_Tool/EEPROM_Tool.exe


t.

**Comment by PBurdelak** [comment]
Thanks for help
I uploaded your firmware.
But right now I cannot turn on the module by connecting MFB to SYS_PWR. Did I broke something or you changed power switch type in any way?

**Comment by tomaskovacik** [comment]
it has all leds turned off and autopower on

but there  is always chance, I f *** it :D

try build your own based on pdf from microchip, you learn something new ;)

**Comment by PBurdelak** [comment]
Ahh LEDs are disabled :D Once again, Thanks for help :)

**Comment by tomaskovacik** [comment]
so it works?

**Comment by PBurdelak** [comment]
Yup, everything works greats
