### ISSUE TITLE
BM23 stuttering audio issue

### ISSUE THREAD

**Issue by audioFail1** [tomaskovacik/IS2020#5]
Hello,

I am having an issue with the BM23  Bluetooth module (IS2023). I saw that you have laid out a breakout board for the BM23, so I am guessing you have some experience with it. 

The Issue:
Audio from the BM23 pauses roughly every 2 seconds for about 300ms. I know the source of the issue is the BM23 and not some other part of the circuit (such as the amplifier). Because this pause occurs on the DT0 line from the BM23 to the amplifier. This was measured on an oscilloscope. 

What I Have Tried:
I have successfully written to the BM23 using the UI, DSP, MPET and EEPROM tools. I have changed all of the configuration settings that I thought may have some impact on this issue (and some that I thought wouldn’t but tried anyway) in an attempt to solve this issue. I have also configured the circuit similar to the reference circuit (provided in the BM23 datasheet), thinking that some noise on one of the pins maybe causing this issue (I will provide a schematic of my test circuit).

I have tried several A2DP sources (several phones and a tablet), with no change in the issue.

I tried a second BM23 chip, thinking it could have been a soldering, overheating or ESD issue. But the second chip performs the same as the first.

I can provide screen shots of my configuration settings for both the UI and DSP tools, if needed.

Any help would be greatly appreciated.

Below is a schematic of my current test circuit using the BM23.

[Speaker1t.PDF](https://github.com/tomaskovacik/IS2020/files/6612349/Speaker1t.PDF)

**Comment by tomaskovacik** [comment]
I have no problem with my bm23
https://github.com/tomaskovacik/kicad-library/blob/master/library/datasheet/BM23/notes.md 

my config: https://github.com/tomaskovacik/kicad-library/tree/master/library/datasheet/BM23
